# Generated by Django 5.0.1 on 2024-01-29 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0003_subscription_blog_post_blog_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_post',
            old_name='blog_cat',
            new_name='blog_categorgs',
        ),
    ]
